spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        prefer-ip-address: true
    openfeign:
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 5000
          finance-service:
            connectTimeout: 3000
            readTimeout: 10000
          analytics-service:
            connectTimeout: 2000
            readTimeout: 2000
    sentinel:
      enabled: true
      eager: true

clients:
  finance-service: http://127.0.0.1:8082
  analytics-service: http://127.0.0.1:8083

logging:
  level:
    root: INFO
    com.javaee.donation.viewer: INFO
