spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        prefer-ip-address: true
    openfeign:
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 8000
          finance-service:
            connectTimeout: 3000
            readTimeout: 15000
          analytics-service:
            connectTimeout: 3000
            readTimeout: 8000
    sentinel:
      enabled: true
      eager: true

server:
  tomcat:
    threads:
      max: 200
      min-spare: 10
    accept-count: 100
    max-connections: 10000

clients:
  finance-service: http://127.0.0.1:8082
  analytics-service: http://127.0.0.1:8083

logging:
  level:
    root: INFO
    com.javaee.donation.viewer: INFO
